### ISSUE TITLE
Silent (/cp) run not silent (enough)

### ISSUE THREAD

**Issue by janfux** [mirinsoft/CleanmgrPlus#7]
If you run "cleanmgr+.exe /cp:<profile>.cleanup" from a script, it will still display a "Cleanmgr+ command line mode has been successfully completed" prompt at the end of the run. This only closes when "OK" is clicked, while the program stays open. This inhibits using it in an automated fashion and contradicts the "completely silent run" explanation of the "cp" command line switch. Please make it either configurable wether the summary is shown or add a timeout to the "ok" button.

**Comment by Belim** [comment]
I've added a new  `/auto /nowindow ` parameter to cli in release https://github.com/mirinsoft/CleanmgrPlus/releases/tag/1.33.1050

**Comment by janfux** [comment]
Thank you very much! Really appreciate this tool 🥇

**Comment by mark-hallman** [comment]
Hello,  I am also wanting to script the execution of CleanmgrPlus and I am still getting the "successfully completed" popup at the completion of the run.  I'm using version 1.35.  My command that I am testing with is

`cleanmgr+.exe /auto /nowindow`

I need my script to continue to run without manually answering the popup.  I'm I using the switching incorrectly?  Is there some other way to accomplish this?

Thanks!

**Comment by Dragodraki** [comment]
I have to mention that the issue still exists: 
With using /nowindow parameter only, the message box can be suppressed but the GUI is still shown for the blink of an eye. Thats because the main process seems to be hidden but it spwans another one that is visible for about 1 seccond.

Please, can you tell me how to suppress the GUI entirely?
